server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 6000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: -1
  data:
    mongodb:
      uri: mongodb://localhost:27017/demo?maxIdleTimeMS=60000


mybatis:
  mapper-locations: mapper,com/springboot/demo/mapper/dnf
  type-aliases-package: com.springboot.demo.entity,com.springboot.demo.entity.*

logging:
  level:
    com:
      springboot:
        demo:
          mapper: debug
shiro:
  enabled: false
